### ISSUE TITLE
No option to add bridged vnet jail

### ISSUE THREAD

**Issue by tschettervictor** [JRGTH/xigmanas-bastille-extension#4] opened 2024-08-30 17:29 UTC
Hey @JRGTH could you make it possibe to create a bridged vnet jail via the GUI? Right now this isn't possible.

**Comment by JRGTH** [comment] 2024-09-02 22:19
Hi, I'm quite busy ATM but looks like that may be an easy yet useful option to do, I will take a look about it on weekend and update files accordingly.
Regards

**Comment by cookiemonsteruk** [comment] 2024-09-02 22:44
I did find this deficiency myself today. I'm struggling to get out of the jail at the moment. Trying different thiings at the moment.
And I did also find a few gremlins OR more likely, unknown ways to do what I want to do.

**Comment by tschettervictor** [comment] 2024-09-02 23:01
Thanks! No rush.

**Comment by cookiemonsteruk** [comment] 2024-09-03 15:09
@tschettervictor have you been able to create a VNET jail from bastille extension that connects out to the internet? Can we compare configs if so?

**Comment by tschettervictor** [comment] 2024-09-04 01:02
Yes I have, but not a VNET one. Only a NAT jail. 
I create all my jails from the command line right now, as it is fairly straightforward, and all my jails are VNET jails.

The first thing I do on XigmaNAS is create a bridge and move my main IP on to the bridge. Then I link all my jails to it using this command.

bastille create -B -V jailname 14.1-RELEASE 192.168.x.x/24 bridge0

This creates a VNET jail connected to my bridge, and in my local network.

**Comment by cookiemonsteruk** [comment] 2024-09-04 08:56
thanks for that. I will for now continue struggling to see if I can make it work with cbsd (also failing to work reliably on XN) and probably try this for bastille in parallel.
> The first thing I do on XigmaNAS is create a bridge and move my main IP on to the bridge. Then I link all my jails to it using this command.
Does that move survive reboots, ie, make it to the config file?

**Comment by cookiemonsteruk** [comment] 2024-09-04 10:21
> Does that move survive reboots, ie, make it to the config file?
Answering my own question, I can see XN's UI has the ability to create bridges. Might try this method.

**Comment by tschettervictor** [comment] 2024-09-04 11:07
> > Does that move survive reboots, ie, make it to the config file?
> > Answering my own question, I can see XN's UI has the ability to create bridges. Might try this method.

It absolutely survives reboots. That is the right want to do networking on BSD if you used jails or VMs. Use a bridge.

**Comment by cookiemonsteruk** [comment] 2024-09-04 13:00
Right. How do you manage the persistance of NATing the VNET jails in XN, so they can reach out of the XN machine's own jail networks and out to the LAN it sits in, and open internet after?

**Comment by cookiemonsteruk** [comment] 2024-09-04 15:49
Are you mixing concepts or am I not explaining or there is a gap in my own undersanding.
A freebsd jail is what it is and shares the host ip address. A VNET jail has as main difference its own network stack, so does not share the ip of the host and has its own one.
I fail to see why you would equate the latter with a virtual machine and a docker container with NAT.
What I want is a thin jail with VNET so can have its own ip address, *and* for it to be able to reach the internet and be reachable from the internet through my separate firewall where I'll have a reverse proxy like haproxy or nginx. This jail with an RFC1918 ip will be the real server. I do not know if this VNET jail would by default have its network stack reachable from a network outside the host's range for jails and therefore require NAT at the host.

**Comment by cookiemonsteruk** [comment] 2024-09-04 16:07
> I only equate it because of the networking. Docker networking by default is NAT-type.
I understand that now.
I'm rebooting again for some reason either bastille or more likely cbsd has created 5 bridges.
It's driving me mad how impossible it is to work with jails in XN at the moment.
I need to figure out which framework has created which bridge before I go and create a fresh one to try your method.

**Comment by tschettervictor** [comment] 2024-09-04 16:09
> > I only equate it because of the networking. Docker networking by default is NAT-type.
> > I understand that now.
> > I'm rebooting again for some reason either bastille or more likely cbsd has created 5 bridges.
> > It's driving me mad how impossible it is to work with jails in XN at the moment.
> > I need to figure out which framework has created which bridge before I go and create a fresh one to try your method.

I know what you mean, but I don’t worry about it. I create my bridge0 interface, then link all my jails to that.

**Comment by tschettervictor** [comment] 2024-09-04 16:14
I’ve never been able to make CBSD work properly. I mostly use iocage (TrueNAS) but since CORE is dead I’m probably migrating to XigmaNAS.

**Comment by cookiemonsteruk** [comment] 2024-09-04 16:24
Right now rebooted. CBSD jails stopped and that removed the spurious bridges.
Started the VNET jail created with bastille add-on and yeah, no network access. Unclear from thread if needs manually adding pf or something like to create the required rdr for NAT but see:
```
@xigmanas ~]$ ifconfig
vmx0: flags=8863<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=4e403bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6,NOMAP>
        ether 00:0c:29:c9:ee:79
        inet 192.168.5.5 netmask 0xffffff00 broadcast 192.168.5.255
        media: Ethernet autoselect
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x2
        inet 127.0.0.1 netmask 0xff000000
        groups: lo
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
cbsd0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: CBSD
        ether 58:9c:fc:10:80:41
        inet 172.16.0.1 netmask 0xffffff00 broadcast 172.16.0.255
        id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
        maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
        root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
        groups: bridge
        nd6 options=9<PERFORMNUD,IFDISABLED>
@xigmanas ~]$ ifconfig
vmx0: flags=8963<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=4a400b9<RXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,VLAN_HWTSO,RXCSUM_IPV6,NOMAP>
        ether 00:0c:29:c9:ee:79
        inet 192.168.5.5 netmask 0xffffff00 broadcast 192.168.5.255
        media: Ethernet autoselect
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x2
        inet 127.0.0.1 netmask 0xff000000
        groups: lo
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
cbsd0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: CBSD
        ether 58:9c:fc:10:80:41
        inet 172.16.0.1 netmask 0xffffff00 broadcast 172.16.0.255
        id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
        maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
        root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
        groups: bridge
        nd6 options=9<PERFORMNUD,IFDISABLED>
vmx0bridge: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        ether 58:9c:fc:10:ff:e8
        id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
        maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
        root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
        member: e0a_bastille0 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
                ifmaxaddr 0 port 5 priority 128 path cost 2000
        member: vmx0 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
                ifmaxaddr 0 port 1 priority 128 path cost 2000
        groups: bridge
        nd6 options=9<PERFORMNUD,IFDISABLED>
e0a_bastille0: flags=8963<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: vnet host interface for Bastille jail nextcloud
        options=8<VLAN_MTU>
        ether 02:20:98:c9:ee:79
        hwaddr 02:76:a5:9a:f0:0a
        groups: epair
        media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>

@xigmanas ~]$ sudo bastille console nextcloud
[nextcloud]:
root@nextcloud:~ # ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
        inet 127.0.0.1 netmask 0xff000000
        groups: lo
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
vnet0: flags=8863<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=8<VLAN_MTU>
        ether 0e:20:98:c9:ee:79
        hwaddr 02:76:a5:9a:f0:0b
        inet 192.168.5.158 netmask 0xffffff00 broadcast 192.168.5.255
        groups: epair
        media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
root@nextcloud:~ # ping 192.168.5.1
PING 192.168.5.1 (192.168.5.1): 56 data bytes
ping: sendto: Host is down
ping: sendto: Host is down
^C
--- 192.168.5.1 ping statistics ---
7 packets transmitted, 0 packets received, 100.0% packet loss
root@nextcloud:~ #
```

**Comment by tschettervictor** [comment] 2024-09-04 18:12
You need to specify -B and -V when creating using the bridge. That way it will set your default gateway as well.

**Comment by cookiemonsteruk** [comment] 2024-09-04 18:37
> How did you create the jail? GUI? CLI?

So far all with the GUI. I haven't yet started using CLI only for jails because I wanted to a) the jails to be visible on the XN UI;  b) test for CBSD so that the author could get the engagement he asked for when he volunteered to create his extension and nobody took it up; c) I have some old bastille non-VNET jails I wanted to test the current state of the extension,
Additionally, since XN is not a full OS and doesn't include many utilities, to manage jails, extensions have had to include them. So in a way they are necessary but that is something I'm interested in verifying. I am not certain of it at the moment, having been away from XN for a while.

**Comment by tschettervictor** [comment] 2024-09-04 20:02
> > How did you create the jail? GUI? CLI?
> 
> So far all with the GUI. I haven't yet started using CLI only for jails because I wanted to a) the jails to be visible on the XN UI; b) test for CBSD so that the author could get the engagement he asked for when he volunteered to create his extension and nobody took it up; c) I have some old bastille non-VNET jails I wanted to test the current state of the extension, Additionally, since XN is not a full OS and doesn't include many utilities, to manage jails, extensions have had to include them. So in a way they are necessary but that is something I'm interested in verifying. I am not certain of it at the moment, having been away from XN for a while.

I understand your point about CBSD. I’d like to see it supported more too.

Your jails will still show if you create them via CLI. The GUI just makes it “easier” to manage visually.

as for Bastille, it is a standalone program that doesn’t have any dependencies.

**Comment by JRGTH** [comment] 2024-09-06 02:37
@[tschettervictor](https://github.com/tschettervictor)
The option to create externally bridged vnet jails thought the webgui has been added here: https://github.com/JRGTH/xigmanas-bastille-extension/commit/21566c34e95b4519271c3db18860f8541c80fa79

Please test and let me know if working in order to close the issue.
Regards

**Comment by tschettervictor** [comment] 2024-09-06 03:01
Hmmm. It works but no internet. I think you need to also include the -V in the create command for it to be able to reach the internet.

**Comment by JRGTH** [comment] 2024-09-06 03:43
> Hmmm. It works but no internet. I think you need to also include the -V in the create command for it to be able to reach the internet.
> 
> I think it would be more practical to have the VNET tick box add the -V switch and the Bridge tick box add the -B switch.

Hi thanks for the report, between only one option for VNET can be used as `-B` already includes the `-V` in the `create.sh` scrips, having both options may broke the installation.

As for no internet that may be a network issue or a BastilleBSD framework issue but I can test this on VM later on the weekend for confirmation.

Regards

**Comment by cookiemonsteruk** [comment] 2024-09-06 07:05
I did all sorts of tests last night (see above) and no internet with -B to a bridge on XN that includes only the LAN interface  and -V .
Something is missing and couldn't figure out what.

**Comment by JRGTH** [comment] 2024-09-06 08:01
Hello, I've updated the config file also to specify `pf.conf` file path under ***[Extensions > Bastille > Configuration]***
Execute this commands one by one to update Bastille Extension and preserving current config:
```
bastille-init -u
bastille-init bastillebsd_update
bastille-init
```

**Comment by cookiemonsteruk** [comment] 2024-09-06 08:08
On it @JRGTH . I destroyed the jails last night in desperation so it'll be pretty clean already. One moment please

**Comment by cookiemonsteruk** [comment] 2024-09-06 08:11
Expected?
```
xigmanas: ~# bastille-init -u
Looking for new bastille package!
/mnt/Raid5Disk/bastille/update/bastille               8747  B  114 MBps    00s
bastille is on the latest version!
Looking for new Extension package!
fetch: https://raw.githubusercontent.com/JRGTH/xigmanas-bastille-extension/master/version: Address family for host not supported
Error: A problem has occurred while fetching version file.
```

**Comment by cookiemonsteruk** [comment] 2024-09-06 08:21
Your suggestion please, but I could try both. I have created a bridge on XN which contains the XN LAN interface only as a member to try adding the VNET jail's interface to so that it could reach the internet.
Shoudl I create the new jail after this update of the extension selecting the bridge, or leave it as "normal" with the LAN interface, in my case vmx0 ?

**Comment by cookiemonsteruk** [comment] 2024-09-06 08:56
Unfortunately it hasn't worked yet. Any ideas what I might have missed? What I've done:
1. Created a new jail and ticked only the new "Enable Bridge VNET (VIMAGE) option. It is a thin jail. Base release same as host 13.3. The selected network interface is the exisitng bridge bridge0 that currently only has the XN LAN interface.
2. Went to XN's UI Network > Interface Management and looked at the existing bridge configuration. Only the LAN was still a member, as expected. There I selected the new interface that I failed to note the name of.
3. Reboot the host (mandatory after modifying the network interface settings)
4. After reboot, checked the ifconfig on host, then started the jail, tested connection out to internet and still failing. Here are the settings:
NOTE: My LAN network is 192.168.5.0/24. XN host LAN ip is 192.168.5.5 . Jail is given ip in bastille of 192.168.5.158

```
## Prior to reboot ##
xigmanas: ~# bastille console nextcloud
[nextcloud]:
root@nextcloud:~ # ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
        inet 127.0.0.1 netmask 0xff000000
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: lo
vnet0: flags=8863<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=8<VLAN_MTU>
        ether 02:e2:b2:f2:60:0b
        hwaddr 02:e2:b2:f2:60:0b
        inet 192.168.5.158 netmask 0xffffff00 broadcast 192.168.5.255
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
        status: active
        groups: epair
root@nextcloud:~ # netstat -rn
Routing tables

Internet:
Destination        Gateway            Flags     Netif Expire
default            192.168.5.1        UGS       vnet0
127.0.0.1          link#1             UH          lo0
192.168.5.0/24     link#2             U         vnet0
192.168.5.158      link#2             UHS         lo0

Internet6:
Destination                       Gateway                       Flags     Netif Expire
::/96                             ::1                           URS         lo0
::1                               link#1                        UHS         lo0
::ffff:0.0.0.0/96                 ::1                           URS         lo0
fe80::/10                         ::1                           URS         lo0
fe80::%lo0/64                     link#1                        U           lo0
fe80::1%lo0                       link#1                        UHS         lo0
ff02::/16                         ::1                           URS         lo0
root@nextcloud:~ # ping 192.168.5.5
PING 192.168.5.5 (192.168.5.5): 56 data bytes
64 bytes from 192.168.5.5: icmp_seq=0 ttl=64 time=0.055 ms
64 bytes from 192.168.5.5: icmp_seq=1 ttl=64 time=0.200 ms
^C
--- 192.168.5.5 ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.055/0.128/0.200/0.073 ms
root@nextcloud:~ # ping 192.168.5.1
PING 192.168.5.1 (192.168.5.1): 56 data bytes
ping: sendto: Host is down
ping: sendto: Host is down
ping: sendto: Host is down
ping: sendto: Host is down
^C
--- 192.168.5.1 ping statistics ---
9 packets transmitted, 0 packets received, 100.0% packet loss
root@nextcloud:~ # exit
logout

xigmanas: ~# exit
logout
[@xigmanas ~]$ exit
logout
Connection to 192.168.5.5 closed.
##Reboot from here##
penguin@UK-LHFS5QL3:~$ ssh 192.168.5.5
(@192.168.5.5) Password for @xigmanas.moomooland:
Last login: Fri Sep  6 09:09:37 2024 from 192.168.5.216
Welcome to XigmaNAS!
[@xigmanas ~]$ su -
Password:
xigmanas: ~# ifconfig
vmx0: flags=8963<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=4e403bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6,NOMAP>
        ether 00:0c:29:c9:ee:79
        inet 192.168.5.5 netmask 0xffffff00 broadcast 192.168.5.255
        media: Ethernet autoselect
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x2
        inet 127.0.0.1 netmask 0xff000000
        groups: lo
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
bridge0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        ether 58:9c:fc:10:80:41
        id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
        maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
        root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
        member: vmx0 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
                ifmaxaddr 0 port 1 priority 128 path cost 2000
        groups: bridge
        nd6 options=9<PERFORMNUD,IFDISABLED>

## Post reboot and starting the jail from here ###
xigmanas: ~# ifconfig
vmx0: flags=8963<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=4a400b9<RXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,VLAN_HWTSO,RXCSUM_IPV6,NOMAP>
        ether 00:0c:29:c9:ee:79
        inet 192.168.5.5 netmask 0xffffff00 broadcast 192.168.5.255
        media: Ethernet autoselect
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x2
        inet 127.0.0.1 netmask 0xff000000
        groups: lo
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
bridge0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        ether 58:9c:fc:10:80:41
        id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
        maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
        root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
        member: e0a_nextcloud flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
                ifmaxaddr 0 port 4 priority 128 path cost 2000
        member: vmx0 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
                ifmaxaddr 0 port 1 priority 128 path cost 2000
        groups: bridge
        nd6 options=9<PERFORMNUD,IFDISABLED>
e0a_nextcloud: flags=8963<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=8<VLAN_MTU>
        ether 02:4a:de:8f:31:0a
        groups: epair
        media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
xigmanas: ~# bastille console nextcloud
[nextcloud]:
root@nextcloud:~ # ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
        inet 127.0.0.1 netmask 0xff000000
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: lo
vnet0: flags=8863<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=8<VLAN_MTU>
        ether 02:4a:de:8f:31:0b
        hwaddr 02:4a:de:8f:31:0b
        inet 192.168.5.158 netmask 0xffffff00 broadcast 192.168.5.255
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
        status: active
        groups: epair
root@nextcloud:~ # ping 192.168.5.1
PING 192.168.5.1 (192.168.5.1): 56 data bytes
^C
--- 192.168.5.1 ping statistics ---
5 packets transmitted, 0 packets received, 100.0% packet loss
root@nextcloud:~ # netstat -rn
Routing tables

Internet:
Destination        Gateway            Flags     Netif Expire
default            192.168.5.1        UGS       vnet0
127.0.0.1          link#1             UH          lo0
192.168.5.0/24     link#2             U         vnet0
192.168.5.158      link#2             UHS         lo0

Internet6:
Destination                       Gateway                       Flags     Netif Expire
::/96                             ::1                           URS         lo0
::1                               link#1                        UHS         lo0
::ffff:0.0.0.0/96                 ::1                           URS         lo0
fe80::/10                         ::1                           URS         lo0
fe80::%lo0/64                     link#1                        U           lo0
fe80::1%lo0                       link#1                        UHS         lo0
ff02::/16                         ::1                           URS         lo0
root@nextcloud:~ # traceroute 8.8.8.8
traceroute to 8.8.8.8 (8.8.8.8), 64 hops max, 40 byte packets
 1  * * *
 2  * * *
 3  * * *
^C
root@nextcloud:~ # pfctl -s rules
root@nextcloud:~ # pfctl -s nat
```
It seems like the jail still can only pass network packets between itself and the host.

**Comment by cookiemonsteruk** [comment] 2024-09-06 09:03
Enabled promiscuous mode on the LAN interface vmx0 and retested. Same outcome.

**Comment by cookiemonsteruk** [comment] 2024-09-06 09:05
> @[tschettervictor](https://github.com/tschettervictor) The option to create externally bridged vnet jails thought the webgui has been added here: [21566c3](https://github.com/JRGTH/xigmanas-bastille-extension/commit/21566c34e95b4519271c3db18860f8541c80fa79)
> 
> Please test and let me know if working in order to close the issue.
> 
> P.S. Be aware if XigmaNAS is running under virtualization, it may require "Promiscuous Mode" to be enabled on the interface for the VNET to work properly such as VirtualBox etc.
> 
> Regards

Ah. I am running XN under virtualisation. XN is currenlty a VM on ESXi. I'll check this now.

**Comment by cookiemonsteruk** [comment] 2024-09-06 09:16
Success. ! That was indeed the solution @JRGTH and @tschettervictor. 
Changing the security policy in ESXi for the vswitch to allow promiscuous mode.

**Comment by cookiemonsteruk** [comment] 2024-09-06 09:17
> Hello, I've found the bug, the no internet issue is that bastille is creating a `resolv.conf` in the "jailpath/etc/" rather than copying the host `resolv.conf`, since the jail can't access outside its environment the jail has no internet.
> 
> Just copy the host(XigmaNAS) `resolv.conf` to the "jailpath/etc/" will solve the issue. I will check and commit a fix on the BastilleBSD asap.
> 
> Regards

Nice but that is a different issue (name resolution of course). So now we have  a solution for XN when running virtualised and you found another defect with name resolution. Let me check that quickly now that traffic is finally passing through.

**Comment by cookiemonsteruk** [comment] 2024-09-06 09:19
Not in my case right now:
```
root@nextcloud:~ # traceroute 8.8.8.8
traceroute to 8.8.8.8 (8.8.8.8), 64 hops max, 40 byte packets
 1  OPNsense (192.168.5.1)  0.669 ms  0.402 ms  0.230 ms
 2  host-92-28-192-1.as13285.net (92.28.192.1)  2.874 ms  3.303 ms  1.866 ms
 3  ae50-ner001.msp.as13285.net (78.144.1.33)  2.958 ms  3.625 ms  4.101 ms
 4  ae50-scr001-msp.as13285.net (78.144.1.32)  3.354 ms  12.839 ms  4.282 ms
 5  ae63-scr102.thw.as13285.net (78.144.1.128)  8.615 ms  8.277 ms  9.381 ms
 6  74.125.51.108 (74.125.51.108)  11.042 ms
    74.125.51.110 (74.125.51.110)  10.357 ms
    74.125.51.108 (74.125.51.108)  11.302 ms
^C
root@nextcloud:~ # cat /etc/resolv.conf
# Generated by resolvconf
search moomooland
nameserver 192.168.5.1
```
That is right. The nameserver should be 192.168.5.1. Unless I misunderstand the issue you are pointing to.

**Comment by JRGTH** [comment] 2024-09-06 09:47
Workaround to copy host `resolv.conf` to the jail path added: https://github.com/JRGTH/xigmanas-bastille-extension/commit/7f4cf143a69f9c2bf3e0a95b1763e947155f29ff

**Comment by cookiemonsteruk** [comment] 2024-09-06 09:55
Maybe because I'm on Full not embedded, this is not a problem for me?

**Comment by JRGTH** [comment] 2024-09-06 09:58
Hi, I'm on Full platform and was having the issue here before the quick fix, between will test on embedded to be sure as well.

**Comment by cookiemonsteruk** [comment] 2024-09-06 10:31
I'll check in a moment what those files are like, and although I normally populate the rc.conf in jails, using the bastille ui you created, I haven't had to

**Comment by tschettervictor** [comment] 2024-09-06 13:52
I'm also having issues even with creating a jail from the CLI. I wonder if it isn't bastille that is not correctly doing something.
My /etc/resolv.conf file is the same as the one in XigmaNAS, so it can't really be that.

**Comment by tschettervictor** [comment] 2024-09-06 14:44
I’m on the embedded install.

**Comment by cookiemonsteruk** [comment] 2024-09-06 15:05
In my case https://github.com/JRGTH/xigmanas-bastille-extension/issues/4#issuecomment-2333496044 are my versions. I am on Full install. Also the latest jail for these tests were created from the bastille extension. Earlier ones were from CLI.

**Comment by cookiemonsteruk** [comment] 2024-09-06 15:17
Trying to do a pkg update made me notice my error. Created this latest jail on 11.3 not 13.1 . Got it confused on the dropdown. Too many attempts until late nights.
Arg. Will redo now.

**Comment by tschettervictor** [comment] 2024-09-06 15:53
Internet works? Can you try 14.1? Or don’t you have a test machine. I’m think of trying CBSD, as Bastille development looks kind of dead these days.

bug reports aren’t being answered etc…

**Comment by cookiemonsteruk** [comment] 2024-09-06 16:26
> Internet works? Can you try 14.1? Or don’t you have a test machine. I’m think of trying CBSD, as Bastille development looks kind of dead these days.
> 
> bug reports aren’t being answered etc…

Internet works yes. I can't try 14 I'm afraid because XN is on 13.3.

**Comment by tschettervictor** [comment] 2024-09-06 16:29
> > Internet works? Can you try 14.1? Or don’t you have a test machine. I’m think of trying CBSD, as Bastille development looks kind of dead these days.
> > bug reports aren’t being answered etc…
> 
> Internet works yes. I can't try 14 I'm afraid because XN is on 13.3.

Great. I guess we can close this issue then. The reason you can’t create a VNET jail is because Bastille errors out when trying to create the bridge for it. It errors with “em0 device busy” etc…

So the right way to do it is create the bridge manually, and use that with the new “bridge” option.

**Comment by cookiemonsteruk** [comment] 2024-09-06 16:33
No, that is not the reason but OK to close.

**Comment by JRGTH** [comment] 2024-09-06 23:45
Remember this commits will solve the `resolv.conf` issue by using the WebGUI, you still need to copy the host `resolv.conf` file manually for VNET/Bridged jails created through the CLI, I will issue a fix to the BastilleBSD project asap, but in the meantime I will make `bastille-init` to also check and perform this temporary fix for the CLI users as well.

Regards.

**Comment by tschettervictor** [comment] 2024-09-07 00:33
I did that. I'm still getting a "network unreachable" when doing a ping to anything.

**Comment by JRGTH** [comment] 2024-09-07 01:20
> I did that. I'm still getting a "network unreachable" when doing a ping to anything. EDIT It looks like the jail is not getting an IP address.

I will check this on 14.x and see if the bundled sys files are working as intended asap, on 13.x VNET is working fine and getting internet on my test under a VM with "promiscuous mode" enabled though.
Regards

**Comment by JRGTH** [comment] 2024-09-08 01:26
Hello, I was fully able to create a VNET jail under XigmaNAS 14.1 with full internet access, even with a jail using a lower RELEASE version.

Please refer to this [XigmaNAS forum link](https://www.xigmanas.com/forums/viewtopic.php?p=14329#p14329) to keep this issues section compact.

**Closed** 2024-09-08 01:46 UTC

**Comment by aimass** [comment] 2025-05-01 15:13
> > > Does that move survive reboots, ie, make it to the config file?
> > > Answering my own question, I can see XN's UI has the ability to create bridges. Might try this method.
> 
> It absolutely survives reboots. That is the right want to do networking on BSD if you used jails or VMs. Use a bridge.

It cannot survive reboots because XigmaNAS overwrites BOTH rc.conf and rc.conf.local (the latter seems like a dumb behaviour). So not sure how you get this to work with XigmaNAS w/o some serious hacking.

**Comment by tschettervictor** [comment] 2025-05-01 16:19
> > > > Does that move survive reboots, ie, make it to the config file?
> > > > Answering my own question, I can see XN's UI has the ability to create bridges. Might try this method.
> > 
> > It absolutely survives reboots. That is the right want to do networking on BSD if you used jails or VMs. Use a bridge.
> 
> It cannot survive reboots because XigmaNAS overwrites BOTH rc.conf and rc.conf.local (the latter seems like a dumb behaviour). So not sure how you get this to work with XigmaNAS w/o some serious hacking.

What are you referring to? I can't find the posts you're replying to lol.

**Comment by aimass** [comment] 2025-05-01 18:43
> > > > > Does that move survive reboots, ie, make it to the config file?
> > > > > Answering my own question, I can see XN's UI has the ability to create bridges. Might try this method.
> > > 
> > > 
> > > It absolutely survives reboots. That is the right want to do networking on BSD if you used jails or VMs. Use a bridge.
> > 
> > 
> > It cannot survive reboots because XigmaNAS overwrites BOTH rc.conf and rc.conf.local (the latter seems like a dumb behaviour). So not sure how you get this to work with XigmaNAS w/o some serious hacking.
> 
> What are you referring to? I can't find the posts you're replying to lol.


I was referring to the fact that XigmaNAS will wipe out any changes to rc.conf and rc.conf.local so configuring a proper bridge, adding an IP to it and adding an interface to it is virtually impossible without going to some extreme measure like setting rc.conf.local to 0440 and chflags schg to avoid XigmaNAS from wiping your custom setup. You also have to hack the XML configuration and reboot to avoid ant warnings in the UI and never dare to touch any networking on the Ui ever again.

This applies for cloned interfaces like lo1 and the bastille0 interface as well, for non-VNAT jails. Without these measures I have not been able to make any use of the extension because the neworking doesn't work very well. I also have to use PF and disable the native IPFW firewall. 

There's lots on things that need to improve in XigmaNAS for extensions like this one to be practical for things like MinIO jails or serving iSCSI block devices, etc.

**Comment by tschettervictor** [comment] 2025-05-01 18:47
This isn't exactly true. Everything done via the GUI persists.

I created my bridges using the GUI, and connect all my jails to these bridges without issue.

You need to use the GUI if you want the changes to persist.

**Comment by aimass** [comment] 2025-05-02 15:16
> This isn't exactly true. Everything done via the GUI persists.
> 
> I created my bridges using the GUI, and connect all my jails to these bridges without issue.
> 
> You need to use the GUI if you want the changes to persist.

You're right. I wasn't aware of System > Advanced > rc.conf

Still there are some improvements that we might be able to address and maybe propose a PR to the extension when we understand better what we're doing :-D
